par(mfrow=c(1,4))
our_boxplot(tablo$Var1,names.arg = c("Var1"), main = "Our Boxplot 1", xlab = "X", ylab = "Values", ylim = c(3, 5), color = "salmon")
our_boxplot(tablo$Var2,names.arg = c("Var2"), main = "Our Boxplot 2", xlab = "X", ylab = "Values", ylim = c(15, 25), color = "salmon")
our_boxplot(tablo$Var3,names.arg = c("Var3"), main = "Our Boxplot 3", xlab = "X", ylab = "Values", ylim = c(55, 68), color = "salmon")
our_boxplot(tablo$Var4,names.arg = c("Var4"), main = "Our Boxplot 4", xlab = "X", ylab = "Values", ylim = c(65, 80), color = "salmon")
our_boxplot(tablo$Var5,names.arg = c("Var5"), main = "Our Boxplot 5", xlab = "X", ylab = "Values", ylim = c(65, 80), color = "salmon")
our_boxplot(tablo$Var6,names.arg = c("Var6"), main = "Our Boxplot 6", xlab = "X", ylab = "Values", ylim = c(65, 80), color = "salmon")
our_boxplot(tablo$Var7,names.arg = c("Var7"), main = "Our Boxplot 7", xlab = "X", ylab = "Values", ylim = c(85, 93), color = "salmon")
our_boxplot(tablo$Var8,names.arg = c("Var8"), main = "Our Boxplot 8", xlab = "X", ylab = "Values", ylim = c(13.5, 18), color = "salmon")